# Generated by Django 2.1.5 on 2019-06-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, '尚未啟用'), (1, '已啟用')], default=0, verbose_name='帳戶狀態'),
        ),
    ]
