# Generated by Django 2.1.5 on 2019-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190610_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地區分類'),
        ),
        migrations.AddField(
            model_name='currency',
            name='risk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='風險分類'),
        ),
    ]
