# Generated by Django 2.1.5 on 2019-06-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='國籍'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='type',
            field=models.IntegerField(choices=[(0, '身分證'), (1, '第二證件'), (2, '簽名'), (3, '自拍照')], verbose_name='類型'),
        ),
    ]
