# Generated by Django 2.1.5 on 2019-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(max_length=200, verbose_name='項目名稱')),
                ('value', models.IntegerField(verbose_name='項目值')),
            ],
            options={
                'verbose_name': '雜項設定',
            },
        ),
    ]
