# Generated by Django 2.1.5 on 2019-02-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金額')),
                ('operation', models.IntegerField(choices=[(0, '無效'), (1, '存入'), (2, '提出'), (3, '轉帳')], default=0, verbose_name='操作')),
                ('date', models.DateTimeField(verbose_name='交易時間')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='account.Account', verbose_name='來源帳戶')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='account.Account', verbose_name='目標帳戶')),
            ],
            options={
                'verbose_name': '交易紀錄資料表',
            },
        ),
    ]
