# Generated by Django 2.1.5 on 2019-03-04 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='電話')),
                ('roc_id', models.CharField(max_length=50, verbose_name='身分證號')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
            options={
                'verbose_name': '付款人資料表',
            },
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='負責人'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='operation',
            field=models.IntegerField(choices=[(0, '存入'), (1, '提出'), (2, '轉帳'), (3, '匯款(未完成)'), (4, '匯款(已完成)')], default=0, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='account.Account', verbose_name='目標帳戶'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Payer', verbose_name='付款人'),
        ),
    ]
