# Generated by Django 2.1.5 on 2019-03-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190304_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='roc_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='身分證號'),
        ),
    ]
