# Generated by Django 2.1.5 on 2019-06-10 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190306_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='貨幣類別'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='時間維度(日)'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='export_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='匯出銀行'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='funds',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='資金來源'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='import_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='匯入銀行'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='isExport',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='匯出識別'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='isImport',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='匯入識別'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='時間維度(時)'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='usage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='資金用途'),
        ),
    ]
