# Generated by Django 2.1.5 on 2019-06-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190610_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='payer',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='國籍'),
        ),
    ]
