# Generated by Django 2.1.5 on 2019-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190610_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='date',
            field=models.DateTimeField(default='2019-06-27 09:07:29', verbose_name='交易時間'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='day',
            field=models.DateTimeField(blank=True, default='2019-06-27', null=True, verbose_name='時間維度(日)'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='operation',
            field=models.IntegerField(choices=[(0, '存入'), (1, '提出'), (2, '轉帳'), (3, '匯款(未完成)'), (4, '匯款(已完成)'), (5, '匯款(拒絕)')], default=0, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='time',
            field=models.TimeField(blank=True, default='09:07:29', null=True, verbose_name='時間維度(時)'),
        ),
    ]
