# Generated by Django 2.1.5 on 2019-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20190627_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='date',
            field=models.DateTimeField(default='2019-06-27 09:09:05', verbose_name='交易時間'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='time',
            field=models.TimeField(blank=True, default='09:09:05', null=True, verbose_name='時間維度(時)'),
        ),
    ]
