# Generated by Django 2.1.5 on 2019-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '黑名單列表',
            },
        ),
    ]
