# Generated by Django 2.1.5 on 2019-06-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='nationality',
            field=models.CharField(max_length=200, verbose_name='國籍'),
        ),
    ]
