# Generated by Django 2.1.5 on 2019-06-17 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('operate', models.CharField(max_length=100, verbose_name='操作')),
                ('reason', models.TextField(verbose_name='事由描述')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': '警示紀錄表',
            },
        ),
    ]
