# Generated by Django 2.1.5 on 2019-06-17 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertlog', '0003_auto_20190617_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='日期'),
        ),
    ]
